apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: config-policy-controller-0pyc
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: config-policy-controller-0pyc
    app.kubernetes.io/part-of: config-policy-controller
  name: config-policy-controller-0pyc
spec:
  replicas: 0
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/instance: config-policy-controller-0pyc
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: config-policy-controller-0pyc
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/config-policy-controller/config-policy-controller-0pyc@sha256:2a34b7d3666f6c3609783d991cba2e6608782b2fa9ddcd4530bb87e2a176c9a7
        imagePullPolicy: Always
        name: container-image
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
