apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: config-policy-controller-0pyc
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/config-policy-controller/config-policy-controller-0pyc@sha256:304affc0e231031fa97794d8e4c37c83e1006686ca9184d76e35d10e9159f16d
        name: container-image
        resources: {}
status: {}
