apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: config-policy-controller-0pyc
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/config-policy-controller/config-policy-controller-0pyc@sha256:7b7d1d64974620b05a2206ebe2bc620a4d6625d62794c4200c6b393be460707d
        name: container-image
        resources: {}
status: {}
