apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: config-policy-controller-0pyc
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/crt-redhat-acm-tenant/config-policy-controller/config-policy-controller-0pyc@sha256:de8b4d65a6cb9a984644646ab69d42f5a6c1152219f86072a6b9ae9b5a0edf32
        name: container-image
        resources: {}
status: {}
